'use strict';

// Kamus Basa Dermayu — diambil dari nur10_kamus_alwi.html
// Dipakai bareng oleh: website (nur10_kamus_alwi.html) & bot-alwi.cjs
module.exports = {
  "kula":      { indonesia:"saya",               pasar:"kula (formal)",              kategori:"Kata Ganti" },
  "isun":      { indonesia:"aku",                pasar:"reang / isun",               kategori:"Kata Ganti" },
  "sira":      { indonesia:"kamu",               pasar:"ira / sira",                 kategori:"Kata Ganti" },
  "rika":      { indonesia:"kamu (sopan/tua)",   pasar:"rika",                       kategori:"Kata Ganti" },
  "sampeyan":  { indonesia:"anda",               pasar:"sampeyan",                   kategori:"Kata Ganti" },
  "deweke":    { indonesia:"dia",                pasar:"deweke / wonge",             kategori:"Kata Ganti" },
  "reang":     { indonesia:"saya/aku (akrab)",   pasar:"reang",                      kategori:"Kata Ganti" },
  "ira":       { indonesia:"kamu (akrab)",       pasar:"ira",                        kategori:"Kata Ganti" },
  "sapa":      { indonesia:"siapa",              pasar:"sapa / sapane",              kategori:"Kata Tanya" },
  "pira":      { indonesia:"berapa",             pasar:"pira",                       kategori:"Kata Tanya" },
  "priben":    { indonesia:"bagaimana",          pasar:"priben / kepriben / priwe",  kategori:"Kata Tanya" },
  "ngendi":    { indonesia:"di mana",            pasar:"ngendi / nendi",             kategori:"Kata Tanya" },
  "mengkene":  { indonesia:"begini",             pasar:"mengkene / ngene",           kategori:"Penunjuk"   },
  "mengkonon": { indonesia:"begitu",             pasar:"mengkonon / ngonon",         kategori:"Penunjuk"   },
  "kene":      { indonesia:"sini",               pasar:"kene",                       kategori:"Penunjuk"   },
  "kono":      { indonesia:"situ",               pasar:"kono",                       kategori:"Penunjuk"   },
  "kana":      { indonesia:"sana",               pasar:"kana",                       kategori:"Penunjuk"   },
  "iki":       { indonesia:"ini",                pasar:"iki / kene",                 kategori:"Penunjuk"   },
  "kuen":      { indonesia:"itu",                pasar:"kuen / kaen",                kategori:"Penunjuk"   },
  "mlaku":     { indonesia:"berjalan",           pasar:"mlaku",                      kategori:"Kata Kerja" },
  "turu":      { indonesia:"tidur",              pasar:"turu / merem",               kategori:"Kata Kerja" },
  "mangan":    { indonesia:"makan",              pasar:"mangan / madang / nguntal",  kategori:"Kata Kerja" },
  "nginum":    { indonesia:"minum",              pasar:"nginum / ngorong",           kategori:"Kata Kerja" },
  "adus":      { indonesia:"mandi",              pasar:"adus",                       kategori:"Kata Kerja" },
  "gawe":      { indonesia:"kerja / buat",       pasar:"gawe / kerja",               kategori:"Kata Kerja" },
  "tuku":      { indonesia:"beli",               pasar:"tuku",                       kategori:"Kata Kerja" },
  "tangi":     { indonesia:"bangun tidur",       pasar:"tangi",                      kategori:"Kata Kerja" },
  "lungguh":   { indonesia:"duduk",              pasar:"lungguh / ndodok",           kategori:"Kata Kerja" },
  "manjing":   { indonesia:"masuk",              pasar:"manjing",                    kategori:"Kata Kerja" },
  "metu":      { indonesia:"keluar",             pasar:"metu / mabor",               kategori:"Kata Kerja" },
  "mangkat":   { indonesia:"berangkat",          pasar:"mangkat / OTW",              kategori:"Kata Kerja" },
  "balik":     { indonesia:"pulang",             pasar:"balik / kondur",             kategori:"Kata Kerja" },
  "teka":      { indonesia:"datang",             pasar:"teka / njedul",              kategori:"Kata Kerja" },
  "gawa":      { indonesia:"bawa",               pasar:"gawa",                       kategori:"Kata Kerja" },
  "deleng":    { indonesia:"lihat",              pasar:"deleng / ndeleng",           kategori:"Kata Kerja" },
  "krungu":    { indonesia:"dengar",             pasar:"krungu",                     kategori:"Kata Kerja" },
  "ngomong":   { indonesia:"bicara",             pasar:"ngomong / nggedobos",        kategori:"Kata Kerja" },
  "nyilih":    { indonesia:"pinjam",             pasar:"nyilih / silih",             kategori:"Kata Kerja" },
  "wehi":      { indonesia:"beri",               pasar:"keki / wehi / upai",         kategori:"Kata Kerja" },
  "luru":      { indonesia:"cari",               pasar:"luru / golet",               kategori:"Kata Kerja" },
  "ngladeni":  { indonesia:"melayani",           pasar:"ngladeni",                   kategori:"Kata Kerja" },
  "kesasar":   { indonesia:"tersesat",           pasar:"kesasar / keblinger",        kategori:"Kata Kerja" },
  "cilik":     { indonesia:"kecil",              pasar:"cilik / mrenil",             kategori:"Kata Sifat" },
  "gede":      { indonesia:"besar",              pasar:"gede / gubrag",              kategori:"Kata Sifat" },
  "lara":      { indonesia:"sakit",              pasar:"lara / ngenes",              kategori:"Kata Sifat" },
  "sehat":     { indonesia:"sehat",              pasar:"sehat / seger",              kategori:"Kata Sifat" },
  "pinter":    { indonesia:"pintar",             pasar:"pinter",                     kategori:"Kata Sifat" },
  "bodo":      { indonesia:"bodoh",              pasar:"bodo / gemblung / kenthir",  kategori:"Kata Sifat" },
  "nesu":      { indonesia:"marah",              pasar:"nesu / berengot",            kategori:"Kata Sifat" },
  "seneng":    { indonesia:"senang",             pasar:"seneng / demen",             kategori:"Kata Sifat" },
  "sedih":     { indonesia:"sedih",              pasar:"sedih / mewek",              kategori:"Kata Sifat" },
  "anyar":     { indonesia:"baru",               pasar:"anyar",                      kategori:"Kata Sifat" },
  "lawas":     { indonesia:"lama/usang",         pasar:"lawas / bengen",             kategori:"Kata Sifat" },
  "adoh":      { indonesia:"jauh",               pasar:"adoh",                       kategori:"Kata Sifat" },
  "parek":     { indonesia:"dekat",              pasar:"parek / perek",              kategori:"Kata Sifat" },
  "ayu":       { indonesia:"cantik",             pasar:"ayu / mentes",               kategori:"Kata Sifat" },
  "ganteng":   { indonesia:"tampan",             pasar:"ganteng / bagus",            kategori:"Kata Sifat" },
  "wareg":     { indonesia:"kenyang",            pasar:"wareg / mblendung",          kategori:"Kata Sifat" },
  "luwe":      { indonesia:"lapar",              pasar:"luwe / klenger",             kategori:"Kata Sifat" },
  "panas":     { indonesia:"panas terik",        pasar:"panas / ngentang-ngentang",  kategori:"Kata Sifat" },
  "pegel":     { indonesia:"pegal/capek",        pasar:"pegel / linu / puyeng",      kategori:"Kata Sifat" },
  "apik":      { indonesia:"bagus/keren",        pasar:"apik / becik",               kategori:"Kata Sifat" },
  "esuk":      { indonesia:"pagi",               pasar:"esuk",                       kategori:"Waktu"      },
  "awan":      { indonesia:"siang",              pasar:"awan",                       kategori:"Waktu"      },
  "sore":      { indonesia:"sore",               pasar:"sore",                       kategori:"Waktu"      },
  "wengi":     { indonesia:"malam",              pasar:"wengi / peteng",             kategori:"Waktu"      },
  "bengen":    { indonesia:"dulu/tadi",          pasar:"bengen / dongen",            kategori:"Waktu"      },
  "saiki":     { indonesia:"sekarang",           pasar:"saiki / kien",               kategori:"Waktu"      },
  "mengko":    { indonesia:"nanti",              pasar:"mengko / ngko",              kategori:"Waktu"      },
  "wingi":     { indonesia:"kemarin",            pasar:"wingi",                      kategori:"Waktu"      },
  "sesuk":     { indonesia:"besok",              pasar:"sesuk / suk",                kategori:"Waktu"      },
  "ora":       { indonesia:"tidak",              pasar:"ora / dudu",                 kategori:"Umum"       },
  "mboten":    { indonesia:"tidak (formal)",     pasar:"mboten",                     kategori:"Umum"       },
  "langka":    { indonesia:"tidak ada",          pasar:"langka / laka",              kategori:"Umum"       },
  "ana":       { indonesia:"ada",                pasar:"ana / na",                   kategori:"Umum"       },
  "iwak":      { indonesia:"ikan / lauk",        pasar:"iwak",                       kategori:"Umum"       },
  "banyu":     { indonesia:"air",                pasar:"banyu",                      kategori:"Umum"       },
  "umah":      { indonesia:"rumah",              pasar:"umah / gubug",               kategori:"Umum"       },
  "dalan":     { indonesia:"jalan",              pasar:"dalan",                      kategori:"Umum"       },
  "segara":    { indonesia:"laut",               pasar:"segara / laut",              kategori:"Umum"       },
  "batur":     { indonesia:"teman",              pasar:"batur / jandalan",           kategori:"Umum"       },
  "jih":       { indonesia:"sih / kok",          pasar:"jih (penegas)",              kategori:"Partikel"   },
  "tah":       { indonesia:"kah / tah",          pasar:"tah (tanya/ragu)",           kategori:"Partikel"   },
  "belih":     { indonesia:"bukan? / kan?",      pasar:"belih / lah",                kategori:"Partikel"   },
  "meneng":    { indonesia:"diam",               pasar:"meneng / mendelik",          kategori:"Partikel"   },
  "wedhi":     { indonesia:"pasir",              pasar:"wedhi",                      kategori:"Tukang"     },
  "macek":     { indonesia:"memasang bata/ubin", pasar:"macek / masang",             kategori:"Tukang"     },
  "pancal":    { indonesia:"cangkul",            pasar:"pancal / pacul",             kategori:"Tukang"     },
  "linggis":   { indonesia:"linggis",            pasar:"linggis",                    kategori:"Tukang"     },
  "blebeg":    { indonesia:"papan kayu panjang", pasar:"blebeg",                     kategori:"Tukang"     },
  "pegel":     { indonesia:"pegal/capek",        pasar:"pegel / linu / puyeng",      kategori:"Tukang"     },
};
